# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogOption(object):
    def setupUi(self, DialogOption):
        DialogOption.setObjectName("DialogOption")
        DialogOption.resize(489, 379)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogOption.setWindowIcon(icon)
        DialogOption.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogOption)
        self.buttonBox.setGeometry(QtCore.QRect(170, 340, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(DialogOption)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 161))
        self.groupBox.setObjectName("groupBox")
        self.comb_Lang = QtWidgets.QComboBox(self.groupBox)
        self.comb_Lang.setGeometry(QtCore.QRect(20, 40, 121, 22))
        self.comb_Lang.setObjectName("comb_Lang")
        self.comb_Lang.addItem("")
        self.comb_Lang.addItem("")
        self.comb_Lang.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(DialogOption)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DialogOption.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogOption.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogOption)

    def retranslateUi(self, DialogOption):
        _translate = QtCore.QCoreApplication.translate
        DialogOption.setWindowTitle(_translate("DialogOption", "Option"))
        self.groupBox.setTitle(_translate("DialogOption", "SelectLanguage"))
        self.comb_Lang.setItemText(0, _translate("DialogOption", "ENGLISH"))
        self.comb_Lang.setItemText(1, _translate("DialogOption", "zh_CN"))
        self.comb_Lang.setItemText(2, _translate("DialogOption", "zh_TW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogOption", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DialogOption", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DialogOption", "Tab 3"))
from ..layout import pyimg_rc
