# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_upgrade.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogUpgrade(object):
    def setupUi(self, DialogUpgrade):
        DialogUpgrade.setObjectName("DialogUpgrade")
        DialogUpgrade.resize(381, 302)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/upgrade.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogUpgrade.setWindowIcon(icon)
        DialogUpgrade.setModal(True)
        self.widget = QtWidgets.QWidget(DialogUpgrade)
        self.widget.setGeometry(QtCore.QRect(10, 10, 361, 283))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Btn_Upgrade = QtWidgets.QPushButton(self.widget)
        self.Btn_Upgrade.setMinimumSize(QtCore.QSize(100, 50))
        self.Btn_Upgrade.setIcon(icon)
        self.Btn_Upgrade.setObjectName("Btn_Upgrade")
        self.horizontalLayout_2.addWidget(self.Btn_Upgrade)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogUpgrade)
        QtCore.QMetaObject.connectSlotsByName(DialogUpgrade)

    def retranslateUi(self, DialogUpgrade):
        _translate = QtCore.QCoreApplication.translate
        DialogUpgrade.setWindowTitle(_translate("DialogUpgrade", "Upgrade"))
        self.toolButton.setText(_translate("DialogUpgrade", "..."))
        self.Btn_Upgrade.setText(_translate("DialogUpgrade", "Upgrade"))
import pyimg_rc
