# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_comm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogComm(object):
    def setupUi(self, DialogComm):
        DialogComm.setObjectName("DialogComm")
        DialogComm.resize(292, 247)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/comm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogComm.setWindowIcon(icon)
        DialogComm.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogComm)
        self.buttonBox.setGeometry(QtCore.QRect(-40, 210, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(DialogComm)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 251, 191))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 19, 237, 156))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Lbl_1 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_1.setObjectName("Lbl_1")
        self.verticalLayout.addWidget(self.Lbl_1)
        self.Lbl_2 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_2.setObjectName("Lbl_2")
        self.verticalLayout.addWidget(self.Lbl_2)
        self.Lbl_3 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_3.setObjectName("Lbl_3")
        self.verticalLayout.addWidget(self.Lbl_3)
        self.Lbl_4 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_4.setObjectName("Lbl_4")
        self.verticalLayout.addWidget(self.Lbl_4)
        self.Lbl_5 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_5.setObjectName("Lbl_5")
        self.verticalLayout.addWidget(self.Lbl_5)
        self.Lbl_6 = QtWidgets.QLabel(self.layoutWidget)
        self.Lbl_6.setObjectName("Lbl_6")
        self.verticalLayout.addWidget(self.Lbl_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comb_Comm = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_Comm.setMinimumSize(QtCore.QSize(100, 0))
        self.comb_Comm.setObjectName("comb_Comm")
        self.verticalLayout_2.addWidget(self.comb_Comm)
        self.comb_BaudR = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_BaudR.setObjectName("comb_BaudR")
        self.verticalLayout_2.addWidget(self.comb_BaudR)
        self.comb_DPaity = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_DPaity.setObjectName("comb_DPaity")
        self.verticalLayout_2.addWidget(self.comb_DPaity)
        self.comb_DataBit = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_DataBit.setObjectName("comb_DataBit")
        self.verticalLayout_2.addWidget(self.comb_DataBit)
        self.comb_StopBit = QtWidgets.QComboBox(self.layoutWidget)
        self.comb_StopBit.setObjectName("comb_StopBit")
        self.verticalLayout_2.addWidget(self.comb_StopBit)
        self.Edt_Timeout = QtWidgets.QLineEdit(self.layoutWidget)
        self.Edt_Timeout.setObjectName("Edt_Timeout")
        self.verticalLayout_2.addWidget(self.Edt_Timeout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.Btn_refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_refresh.setIcon(icon1)
        self.Btn_refresh.setObjectName("Btn_refresh")
        self.verticalLayout_3.addWidget(self.Btn_refresh)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(DialogComm)
        self.buttonBox.accepted.connect(DialogComm.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogComm.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogComm)

    def retranslateUi(self, DialogComm):
        _translate = QtCore.QCoreApplication.translate
        DialogComm.setWindowTitle(_translate("DialogComm", "CommSet"))
        self.groupBox.setTitle(_translate("DialogComm", "Comm"))
        self.Lbl_1.setText(_translate("DialogComm", "ComPort"))
        self.Lbl_2.setText(_translate("DialogComm", "BaudRate"))
        self.Lbl_3.setText(_translate("DialogComm", "DataPaity"))
        self.Lbl_4.setText(_translate("DialogComm", "DataBit"))
        self.Lbl_5.setText(_translate("DialogComm", "StopBit"))
        self.Lbl_6.setText(_translate("DialogComm", "Timeout"))
from ..layout import pyimg_rc
