# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogPro(object):
    def setupUi(self, DialogPro):
        DialogPro.setObjectName("DialogPro")
        DialogPro.resize(368, 197)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPro.setWindowIcon(icon)
        DialogPro.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPro)
        self.buttonBox.setGeometry(QtCore.QRect(50, 160, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(DialogPro)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 291, 121))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(50, 30, 187, 76))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Lbl_DevAddr = QtWidgets.QLabel(self.widget)
        self.Lbl_DevAddr.setObjectName("Lbl_DevAddr")
        self.verticalLayout_2.addWidget(self.Lbl_DevAddr)
        self.Lbl_Product = QtWidgets.QLabel(self.widget)
        self.Lbl_Product.setObjectName("Lbl_Product")
        self.verticalLayout_2.addWidget(self.Lbl_Product)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Edt_DevAddr = QtWidgets.QLineEdit(self.widget)
        self.Edt_DevAddr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Edt_DevAddr.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.Edt_DevAddr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Edt_DevAddr.setObjectName("Edt_DevAddr")
        self.verticalLayout.addWidget(self.Edt_DevAddr)
        self.comb_Product = QtWidgets.QComboBox(self.widget)
        self.comb_Product.setObjectName("comb_Product")
        self.verticalLayout.addWidget(self.comb_Product)
        self.Edt_AcqCyc = QtWidgets.QLineEdit(self.widget)
        self.Edt_AcqCyc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Edt_AcqCyc.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.Edt_AcqCyc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Edt_AcqCyc.setObjectName("Edt_AcqCyc")
        self.verticalLayout.addWidget(self.Edt_AcqCyc)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(DialogPro)
        self.buttonBox.accepted.connect(DialogPro.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogPro.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogPro)

    def retranslateUi(self, DialogPro):
        _translate = QtCore.QCoreApplication.translate
        DialogPro.setWindowTitle(_translate("DialogPro", "LoadProduct"))
        self.groupBox.setTitle(_translate("DialogPro", "Select"))
        self.Lbl_DevAddr.setText(_translate("DialogPro", "DevAddr"))
        self.Lbl_Product.setText(_translate("DialogPro", "Product"))
        self.label.setText(_translate("DialogPro", "AcqCyc"))
from ..layout import pyimg_rc
